---
apiVersion: v1
kind: Namespace
metadata:
  name: whoami
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  namespace: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "32Mi"
            cpu: "50m"  
        image: traefik/whoami
        env:
          - name: WHOAMI_NAME
            value: whoami-k8s
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: whoami
  labels:
    app: whoami
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: whoami
  selector:
    app: whoami
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ing
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`whoami.${CLUSTERNAME}.${DOMAINNAME}`)
    kind: Rule
    services:
    - name: whoami
      port: 80
  tls: {}
  # tls:
  #   certResolver: le
